get http://localhost:5000
###
get http://localhost:5000/api/users
###
get http://localhost:5000/api/profile
###
get http://localhost:5000/api/posts/
###
get http://localhost:5000/api/auth 
###
post http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "whoami",
  "email": "whoami@abc.com",
  "password": "123123"
}